name = "monorepo-hono-web"
compatibility_date = "2024-01-01"

[build]
command = "cd apps/web && bun install && bun run build"
pages_build_output_dir = "apps/web/.next"

[build.environment]
NODE_VERSION = "18"
ENV = "production"

[env.production.vars]
ENV = "production"

[env.staging.vars]
ENV = "staging"

[env.development.vars]
ENV = "development"
