name = "hono-learn"
main = "src/index.ts"
compatibility_date = "2024-12-24"

# Local development KV
[[kv_namespaces]]
binding = "KV_BETTER_AUTH"
id = "acfb6448369840a1ac00caec6a90c596"
preview_id = "acfb6448369840a1ac00caec6a90c596"

[env.production]
name = "hono-monorepo-production"

# Production KV namespace
[[env.production.kv_namespaces]]
binding = "PRODUCTION_KV_NAMESPACE"
id = "your-production-kv-id-here" # deploy with cli and get id

[[env.production.routes]]
pattern = "hono-monorepo-api.zachuri.com/*"
zone_name = "zachuri.com"

[env.staging]
name = "hono-monorepo-staging"

# Staging KV namespace
[[env.staging.kv_namespaces]]
binding = "STAGING_KV_NAMESPACE"
id = "your-staging-kv-id-here" # deploy with cli and get id

[[env.staging.routes]]
pattern = "hono-monorepo-staging-api.zachuri.com/*"
zone_name = "zachuri.com"


# For public vars

# [env.staging.vars]
# API_HOST = "hono-api.zachuri.com"

# [env.production.vars]
# API_HOST = "hono-api.zachuri.com"
