name = "hono-learn"
main = "src/index.ts"
compatibility_date = "2024-12-24"

[env.production]
name = "hono-monorepo-production"

[[env.production.routes]]
pattern = "hono-monorepo-api.zachuri.com/*"
zone_name = "zachuri.com"

[env.staging]
name = "hono-monorepo-staging"

[[env.staging.routes]]
pattern = "hono-monorepo-staging-api.zachuri.com/*"
zone_name = "zachuri.com"


# For public vars

# [env.staging.vars]
# API_HOST = "hono-api.zachuri.com"

# [env.production.vars]
# API_HOST = "hono-api.zachuri.com"
